import Head from 'next/head';
import EntryForm from './components/EntryForm';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='col-span-9 m-4 min-h-screen'>
				<h1 className='mb-4 text-4xl'>Your Journal</h1>
				<EntryForm />
			</main>
		</>
	);
}
